libbeetroot-1.0.0: beetroot::FileHandler Class Reference
beetroot::FileHandler Class Reference
ROOT file handler.
#include <beetroot/FileHandler.h>
Public Types
enum OpenAs { CREATE, RECREATE, UPDATE, READ }
Enum to delineate file opening options.
Public Member Functions
FileHandler (const std::string &name, const OpenAs &openType=READ)
Default constructor opens a file read-only.
virtual ~FileHandler ()
template<typename T >
T read (const std::string &objectName) const
Read an object from a ROOT file.
template<typename T >
const int write (const T &object, const std::string &objectName="", const std::string &dirName="", const bool overwrite=true)
Write an object to a ROOT file.
virtual void mkdir (const std::string &dirName) const
Make a directory inside a ROOT file.
virtual void cd (const std::string &path="") const
Change to another directory inside a ROOT file.
virtual void mkcd (const std::string &dirName) const
Make a directory inside a ROOT file and change to it.
virtual void ls () const
List the contents of a ROOT file.
virtual std::string name () const
Get the name of a ROOT file.
Detailed Description
ROOT file handler.
File handler to safely open, close, read and write ROOT files.
Author:
James Robinson james.nosp@m..rob.nosp@m.inson.nosp@m.@cer.nosp@m.n.ch
Date:
February 2013
Member Enumeration Documentation
enum beetroot::FileHandler::OpenAs
Enum to delineate file opening options.
Enumerator:
CREATE
RECREATE
UPDATE
READ
Constructor & Destructor Documentation
beetroot::FileHandler::FileHandler (const std::string & name, const OpenAs & openType = READ)
Default constructor opens a file read-only.
virtual beetroot::FileHandler::~FileHandler () virtual
Member Function Documentation
virtual void beetroot::FileHandler::cd (const std::string & path = "") const virtual
Change to another directory inside a ROOT file.
Referenced by write().
virtual void beetroot::FileHandler::ls () const virtual
List the contents of a ROOT file.
virtual void beetroot::FileHandler::mkcd (const std::string & dirName) const virtual
Make a directory inside a ROOT file and change to it.
virtual void beetroot::FileHandler::mkdir (const std::string & dirName) const virtual
Make a directory inside a ROOT file.
virtual std::string beetroot::FileHandler::name () const virtual
Get the name of a ROOT file.
Referenced by read().
template<typename T > T beetroot::FileHandler::read (const std::string & objectName) const inline
Read an object from a ROOT file.
References name().
template<typename T > const int beetroot::FileHandler::write (const T & object, const std::string & objectName = "", const std::string & dirName = "", const bool overwrite = true) inline
Write an object to a ROOT file.
References cd().
The documentation for this class was generated from the following file:
beetroot/FileHandler.h